post http://localhost:3000/register
Content-Type: application/json

{
"username": "prathibha11",
  "name": "prathibha",
  "password": "123456",
  "gender": "female",
  "location": "hyderabad"
}

#######
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

#########
put http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}